version: '3.8'

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

  backend:
    build:
      context: ./flask
      target: builder
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    depends_on:
      - elastic
    networks:
      - homenet

networks:
  homenet:
