# Use the lightweight version of the official Python image
FROM python:3.10-bookworm

# Set the working directory
WORKDIR /usr/src/app

# Copy the current directory contents into the container
COPY . .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Set the environment variable
ENV FLASK_APP=app.py

# Run the application
CMD ["flask", "run", "--host=104.197.143.101", "--port=80"]