name: Install & Compose Up

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_COMPOSE_VERSION: '2.20.3'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    # Checkout the code from repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Manage Docker containers, images, and install Docker if not present
    - name: Docker Management
      run: |
        # Check if Docker is installed
        if command -v docker &>/dev/null; then
          # Stop running containers if any
          CONTAINERS_RUNNING=$(sudo docker ps -aq)
          [ ! -z "$CONTAINERS_RUNNING" ] && sudo docker stop $CONTAINERS_RUNNING || echo "No containers to stop"

          # Remove stopped containers if any
          CONTAINERS_STOPPED=$(sudo docker ps -a -q)
          [ ! -z "$CONTAINERS_STOPPED" ] && sudo docker rm -f $CONTAINERS_STOPPED

          # Prune all unused Docker objects
          sudo docker system prune -a -f --volumes

          # Restart Docker service
          sudo systemctl restart docker
        else
          # Install Docker if not installed
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
        fi

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -SL "https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Build and start Docker Compose services
    - name: Build and Up Docker Compose
      run: |
        sudo chmod 600 traefik/acme.json
        sudo docker-compose -f docker-compose.yml build
        sudo docker-compose -f docker-compose.yml up -d
