name: Install & Compose Up

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_COMPOSE_VERSION: '2.20.3'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker (if not present)
      run: |
        if ! command -v docker &>/dev/null; then
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
        fi

    - name: Install Docker Compose
      run: |
        sudo curl -SL "https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and Up Docker Compose
      run: |
        sudo docker-compose -f docker-compose.yml build
        sudo docker-compose -f docker-compose.yml up -d
