name: make docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_COMPOSE_VERSION: '2.20.3'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop any running Docker containers, Prune everything and Install/Restart Docker (if present)
      run: make docker

