name: Install & Compose Up

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_COMPOSE_VERSION: '2.20.3'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop any running Docker containers, Prune everything and Install/Restart Docker (if present)
      run: |
        if command -v docker &>/dev/null; then
          CONTAINERS_RUNNING=$(sudo docker ps -aq)
          if [ ! -z "$CONTAINERS_RUNNING" ]; then
            sudo docker stop $CONTAINERS_RUNNING
          else
            echo "No containers to stop"
          fi

          CONTAINERS_STOPPED=$(sudo docker ps -a -q)
          if [ ! -z "$CONTAINERS_STOPPED" ]; then
            sudo docker rm -f $CONTAINERS_STOPPED
          fi
          sudo systemctl restart docker
        else
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
        fi

    - name: Install Docker Compose
      run: |
        sudo curl -SL "https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and Up Docker Compose
      run: |
        sudo chmod 600 traefik/acme.json
        sudo docker-compose -f docker-compose.yml build
        sudo docker-compose -f docker-compose.yml up -d

    - name: Show Flask logs
      run: |
        sudo docker-compose logs server